### PR TITLE
Welp, more icons, because i'm bored, so expect one or two batch tonight

### PR DESCRIPTION
**Pull request by AzhamProdLive**

### CODE REVIEW

**Comment by PonyLucky** [comment]
Did you tried the `canal_plus_logo.svg` ?

He seems too wide for me. Even if this is the official one...

**Comment by AzhamProdLive** [comment]
I tried and seems to work, but yea it do be kinda funky, you can omit it if you want, I haven't found a smaller logo for it sadly

**Comment by PonyLucky** [comment]
For Linguee, you can get a better version on the website (inspect the logo then click on the `:before` to see the base64 svg).

Linguee

**Comment by AzhamProdLive** [comment]
Gonna switch them, i'll be right back

**Comment by PonyLucky** [comment]
As for canal+ i'll add (while keeping the officiql logo) a striped logo with just (c+)

**Comment by PonyLucky** [comment]
Anyway thanks mate

**Comment by AzhamProdLive** [comment]
> As for canal+ i'll add (while keeping the officiql logo) a striped logo with just (c+)
I'll try to do that later on then

> Anyway thanks mate
No problems, happy to help :+1:

**Comment by PonyLucky** [comment]
Here is the canal+ logos ;)

`canal-plus.svg`
canal-plus

`canal-plus-white.svg`
canal-plus-white

**Comment by AzhamProdLive** [comment]
Well, you beat me to it, I was currently making an edit of the big one into the same idea you did lmao

Well, yoink those and adds them

**Comment by PonyLucky** [comment]
#6

**Pull request merged**
